// import type { Metadata } from "next";
// import { Html } from "next/document";


import Link from 'next/link';
// import Script from "next/script";
import { Geist, Geist_Mono } from "next/font/google";

import "./../../public/css/bootstrap.min.css";
import "./../../public/css/style.css";
// import "./../../public/lib/lightbox/css/lightbox.min.css";
// import "/lib/owlcarousel/assets/owl.carousel.min.css";


// import 'owl.carousel/dist/assets/owl.carousel.css';
// import 'owl.carousel';

import Preloader from "@/components/Preloader";

import Header from "@/components/Header";
import Footer from "@/components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata: Metadata = {
//   title: "Fruitables Next App",
//   description: "Fruitables Ecommerce store generated by create next app",
// };

export default function RootLayout({ children }: Readonly <{children: React.ReactNode; }>) {

  

  return (
    <>
        {/* <Preloader /> */}
        <Header />
        <div>{children}</div>
        <Footer />
    </>
  );
}
